import { DayView } from "@/modules/be-planner/components/DayView";
import Head from "next/head";

export default function BEPlanner() {
    return (
        <>
            <Head>
                <title>BE Playnlist</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="manifest" href="/planner.webmanifest" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DayView />
        </>
    );
}
