import Head from 'next/head'
import { Inter } from '@next/font/google'
import { CommonPageWrapper } from '@/modules/common/CommonPageWrapper'
import { HomePage } from '@/modules/home/HomePage'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Oba</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <CommonPageWrapper>
            <HomePage />
          </CommonPageWrapper>
      </main>
    </>
  )
}
