import Head from "next/head";
import Pokedex from "@/modules/pokedex/pokedex";
import { IPokemonIndex } from "@/modules/pokedex/types";
import PokemonData from "./api/allPokedexData.json";

interface IPokedexProps {
    pokemonIndex: IPokemonIndex;
    listOfPokemonIds: string[];
}

export default function PokedexIndex({
    pokemonIndex,
    listOfPokemonIds,
}: IPokedexProps) {
    return (
        <>
            <Head>
                <title>Pokedex</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Pokedex
                    pokemonIndex={pokemonIndex}
                    listOfPokemonIds={listOfPokemonIds}
                />
            </main>
        </>
    );
}

export function getStaticProps() {
    return {
        props: {
            pokemonIndex: PokemonData,
            listOfPokemonIds: Object.keys(PokemonData),
        },
    };
}
