import Head from "next/head";
import Pokedex from "@/modules/pokedex/pokedex";

export default function PokedexIndex() {
    return (
        <>
            <Head>
                <title>Pokedex</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Pokedex />
            </main>
        </>
    );
}
